module.exports = {
    up: (queryInterface) => {
        return queryInterface.bulkInsert(
            'pays',
            [
                { code: 'AFG', nom: "Afghanistan" },
                { code: 'ALB', nom: "Albanie" },
                { code: 'ATA', nom: "Antarctique" },
                { code: 'DZA', nom: "Algérie" },
                { code: 'ASM', nom: "Samoa Américaines" },
                { code: 'AND', nom: "Andorre" },
                { code: 'AGO', nom: "Angola" },
                { code: 'ATG', nom: "Antigua-et-Barbuda" },
                { code: 'AZE', nom: "Azerbaïdjan" },
                { code: 'ARG', nom: "Argentine" },
                { code: 'AUS', nom: "Australie" },
                { code: 'AUT', nom: "Autriche" },
                { code: 'BHS', nom: "Bahamas" },
                { code: 'BHR', nom: "Bahreïn" },
                { code: 'BGD', nom: "Bangladesh" },
                { code: 'ARM', nom: "Arménie" },
                { code: 'BRB', nom: "Barbade" },
                { code: 'BEL', nom: "Belgique" },
                { code: 'BMU', nom: "Bermudes" },
                { code: 'BTN', nom: "Bhoutan" },
                { code: 'BOL', nom: "Bolivie" },
                { code: 'BIH', nom: "Bosnie-Herzégovine" },
                { code: 'BWA', nom: "Botswana" },
                { code: 'BVT', nom: "Île Bouvet" },
                { code: 'BRA', nom: "Brésil" },
                { code: 'BLZ', nom: "Belize" },
                { code: 'IOT', nom: "Territoire Britannique de l'Océan Indien" },
                { code: 'SLB', nom: "Îles Salomon" },
                { code: 'VGB', nom: "Îles Vierges Britanniques" },
                { code: 'BRN', nom: "Brunéi Darussalam" },
                { code: 'BGR', nom: "Bulgarie" },
                { code: 'MMR', nom: "Myanmar" },
                { code: 'BDI', nom: "Burundi" },
                { code: 'BLR', nom: "Bélarus" },
                { code: 'KHM', nom: "Cambodge" },
                { code: 'CMR', nom: "Cameroun" },
                { code: 'CAN', nom: "Canada" },
                { code: 'CPV', nom: "Cap-vert" },
                { code: 'CYM', nom: "Îles Caïmanes" },
                { code: 'CAF', nom: "République Centrafricaine" },
                { code: 'LKA', nom: "Sri Lanka" },
                { code: 'TCD', nom: "Tchad" },
                { code: 'CHL', nom: "Chili" },
                { code: 'CHN', nom: "Chine" },
                { code: 'TWN', nom: "Taïwan" },
                { code: 'CXR', nom: "Île Christmas" },
                { code: 'CCK', nom: "Îles Cocos (Keeling)" },
                { code: 'COL', nom: "Colombie" },
                { code: 'COM', nom: "Comores" },
                { code: 'MYT', nom: "Mayotte" },
                { code: 'COG', nom: "République du Congo" },
                { code: 'COD', nom: "République Démocratique du Congo" },
                { code: 'COK', nom: "Îles Cook" },
                { code: 'CRI', nom: "Costa Rica" },
                { code: 'HRV', nom: "Croatie" },
                { code: 'CUB', nom: "Cuba" },
                { code: 'CYP', nom: "Chypre" },
                { code: 'CZE', nom: "République Tchèque" },
                { code: 'BEN', nom: "Bénin" },
                { code: 'DNK', nom: "Danemark" },
                { code: 'DMA', nom: "Dominique" },
                { code: 'DOM', nom: "République Dominicaine" },
                { code: 'ECU', nom: "Équateur" },
                { code: 'SLV', nom: "El Salvador" },
                { code: 'GNQ', nom: "Guinée Équatoriale" },
                { code: 'ETH', nom: "Éthiopie" },
                { code: 'ERI', nom: "Érythrée" },
                { code: 'EST', nom: "Estonie" },
                { code: 'FRO', nom: "Îles Féroé" },
                { code: 'FLK', nom: "Îles (malvinas) Falkland" },
                { code: 'SGS', nom: "Géorgie du Sud et les Îles Sandwich du Sud" },
                { code: 'FJI', nom: "Fidji" },
                { code: 'FIN', nom: "Finlande" },
                { code: 'ALA', nom: "Îles Åland" },
                { code: 'FRA', nom: "France" },
                { code: 'GUF', nom: "Guyane Française" },
                { code: 'PYF', nom: "Polynésie Française" },
                { code: 'ATF', nom: "Terres Australes Françaises" },
                { code: 'DJI', nom: "Djibouti" },
                { code: 'GAB', nom: "Gabon" },
                { code: 'GEO', nom: "Géorgie" },
                { code: 'GMB', nom: "Gambie" },
                { code: 'PSE', nom: "Territoire Palestinien Occupé" },
                { code: 'DEU', nom: "Allemagne" },
                { code: 'GHA', nom: "Ghana" },
                { code: 'GIB', nom: "Gibraltar" },
                { code: 'KIR', nom: "Kiribati" },
                { code: 'GRC', nom: "Grèce" },
                { code: 'GRL', nom: "Groenland" },
                { code: 'GRD', nom: "Grenade" },
                { code: 'GLP', nom: "Guadeloupe" },
                { code: 'GUM', nom: "Guam" },
                { code: 'GTM', nom: "Guatemala" },
                { code: 'GIN', nom: "Guinée" },
                { code: 'GUY', nom: "Guyana" },
                { code: 'HTI', nom: "Haïti" },
                { code: 'HMD', nom: "Îles Heard et Mcdonald" },
                { code: 'VAT', nom: "Saint-Siège (état de la Cité du Vatican)" },
                { code: 'HND', nom: "Honduras" },
                { code: 'HKG', nom: "Hong-Kong" },
                { code: 'HUN', nom: "Hongrie" },
                { code: 'ISL', nom: "Islande" },
                { code: 'IND', nom: "Inde" },
                { code: 'IDN', nom: "Indonésie" },
                { code: 'IRN', nom: "République Islamique d'Iran" },
                { code: 'IRQ', nom: "Iraq" },
                { code: 'IRL', nom: "Irlande" },
                { code: 'ISR', nom: "Israël" },
                { code: 'ITA', nom: "Italie" },
                { code: 'CIV', nom: "Côte d'Ivoire" },
                { code: 'JAM', nom: "Jamaïque" },
                { code: 'JPN', nom: "Japon" },
                { code: 'KAZ', nom: "Kazakhstan" },
                { code: 'JOR', nom: "Jordanie" },
                { code: 'KEN', nom: "Kenya" },
                { code: 'PRK', nom: "République Populaire Démocratique de Corée" },
                { code: 'KOR', nom: "République de Corée" },
                { code: 'KWT', nom: "Koweït" },
                { code: 'KGZ', nom: "Kirghizistan" },
                { code: 'LAO', nom: "République Démocratique Populaire Lao" },
                { code: 'LBN', nom: "Liban" },
                { code: 'LSO', nom: "Lesotho" },
                { code: 'LVA', nom: "Lettonie" },
                { code: 'LBR', nom: "Libéria" },
                { code: 'LBY', nom: "Jamahiriya Arabe Libyenne" },
                { code: 'LIE', nom: "Liechtenstein" },
                { code: 'LTU', nom: "Lituanie" },
                { code: 'LUX', nom: "Luxembourg" },
                { code: 'MAC', nom: "Macao" },
                { code: 'MDG', nom: "Madagascar" },
                { code: 'MWI', nom: "Malawi" },
                { code: 'MYS', nom: "Malaisie" },
                { code: 'MDV', nom: "Maldives" },
                { code: 'MLI', nom: "Mali" },
                { code: 'MLT', nom: "Malte" },
                { code: 'MTQ', nom: "Martinique" },
                { code: 'MRT', nom: "Mauritanie" },
                { code: 'MUS', nom: "Maurice" },
                { code: 'MEX', nom: "Mexique" },
                { code: 'MCO', nom: "Monaco" },
                { code: 'MNG', nom: "Mongolie" },
                { code: 'MDA', nom: "République de Moldova" },
                { code: 'MSR', nom: "Montserrat" },
                { code: 'MAR', nom: "Maroc" },
                { code: 'MOZ', nom: "Mozambique" },
                { code: 'OMN', nom: "Oman" },
                { code: 'NAM', nom: "Namibie" },
                { code: 'NRU', nom: "Nauru" },
                { code: 'NPL', nom: "Népal" },
                { code: 'NLD', nom: "Pays-Bas" },
                { code: 'ANT', nom: "Antilles Néerlandaises" },
                { code: 'ABW', nom: "Aruba" },
                { code: 'NCL', nom: "Nouvelle-Calédonie" },
                { code: 'VUT', nom: "Vanuatu" },
                { code: 'NZL', nom: "Nouvelle-Zélande" },
                { code: 'NIC', nom: "Nicaragua" },
                { code: 'NER', nom: "Niger" },
                { code: 'NGA', nom: "Nigéria" },
                { code: 'NIU', nom: "Niué" },
                { code: 'NFK', nom: "Île Norfolk" },
                { code: 'NOR', nom: "Norvège" },
                { code: 'MNP', nom: "Îles Mariannes du Nord" },
                { code: 'UMI', nom: "Îles Mineures Éloignées des États-Unis" },
                { code: 'FSM', nom: "États Fédérés de Micronésie" },
                { code: 'MHL', nom: "Îles Marshall" },
                { code: 'PLW', nom: "Palaos" },
                { code: 'PAK', nom: "Pakistan" },
                { code: 'PAN', nom: "Panama" },
                { code: 'PNG', nom: "Papouasie-Nouvelle-Guinée" },
                { code: 'PRY', nom: "Paraguay" },
                { code: 'PER', nom: "Pérou" },
                { code: 'PHL', nom: "Philippines" },
                { code: 'PCN', nom: "Pitcairn" },
                { code: 'POL', nom: "Pologne" },
                { code: 'PRT', nom: "Portugal" },
                { code: 'GNB', nom: "Guinée-Bissau" },
                { code: 'TLS', nom: "Timor-Leste" },
                { code: 'PRI', nom: "Porto Rico" },
                { code: 'QAT', nom: "Qatar" },
                { code: 'REU', nom: "Réunion" },
                { code: 'ROU', nom: "Roumanie" },
                { code: 'RUS', nom: "Fédération de Russie" },
                { code: 'RWA', nom: "Rwanda" },
                { code: 'SHN', nom: "Sainte-Hélène" },
                { code: 'KNA', nom: "Saint-Kitts-et-Nevis" },
                { code: 'AIA', nom: "Anguilla" },
                { code: 'LCA', nom: "Sainte-Lucie" },
                { code: 'SPM', nom: "Saint-Pierre-et-Miquelon" },
                { code: 'VCT', nom: "Saint-Vincent-et-les Grenadines" },
                { code: 'SMR', nom: "Saint-Marin" },
                { code: 'STP', nom: "Sao Tomé-et-Principe" },
                { code: 'SAU', nom: "Arabie Saoudite" },
                { code: 'SEN', nom: "Sénégal" },
                { code: 'SYC', nom: "Seychelles" },
                { code: 'SLE', nom: "Sierra Leone" },
                { code: 'SGP', nom: "Singapour" },
                { code: 'SVK', nom: "Slovaquie" },
                { code: 'VNM', nom: "Viet Nam" },
                { code: 'SVN', nom: "Slovénie" },
                { code: 'SOM', nom: "Somalie" },
                { code: 'ZAF', nom: "Afrique du Sud" },
                { code: 'ZWE', nom: "Zimbabwe" },
                { code: 'ESP', nom: "Espagne" },
                { code: 'ESH', nom: "Sahara Occidental" },
                { code: 'SDN', nom: "Soudan" },
                { code: 'SUR', nom: "Suriname" },
                { code: 'SJM', nom: "Svalbard etÎle Jan Mayen" },
                { code: 'SWZ', nom: "Swaziland" },
                { code: 'SWE', nom: "Suède" },
                { code: 'CHE', nom: "Suisse" },
                { code: 'SYR', nom: "République Arabe Syrienne" },
                { code: 'TJK', nom: "Tadjikistan" },
                { code: 'THA', nom: "Thaïlande" },
                { code: 'TGO', nom: "Togo" },
                { code: 'TKL', nom: "Tokelau" },
                { code: 'TON', nom: "Tonga" },
                { code: 'TTO', nom: "Trinité-et-Tobago" },
                { code: 'ARE', nom: "Émirats Arabes Unis" },
                { code: 'TUN', nom: "Tunisie" },
                { code: 'TUR', nom: "Turquie" },
                { code: 'TKM', nom: "Turkménistan" },
                { code: 'TCA', nom: "Îles Turks et Caïques" },
                { code: 'TUV', nom: "Tuvalu" },
                { code: 'UGA', nom: "Ouganda" },
                { code: 'UKR', nom: "Ukraine" },
                { code: 'MKD', nom: "L'ex-République Yougoslave de Macédoine" },
                { code: 'EGY', nom: "Égypte" },
                { code: 'GBR', nom: "Royaume-Uni" },
                { code: 'IMN', nom: "Île de Man" },
                { code: 'TZA', nom: "République-Unie de Tanzanie" },
                { code: 'USA', nom: "États-Unis" },
                { code: 'VIR', nom: "Îles Vierges des États-Unis" },
                { code: 'BFA', nom: "Burkina Faso" },
                { code: 'URY', nom: "Uruguay" },
                { code: 'UZB', nom: "Ouzbékistan" },
                { code: 'VEN', nom: "Venezuela" },
                { code: 'WLF', nom: "Wallis et Futuna" },
                { code: 'WSM', nom: "Samoa" },
                { code: 'YEM', nom: "Yémen" },
                { code: 'SCG', nom: "Serbie-et-Monténégro" },
                { code: 'ZMB', nom: "Zambie" },
            ],
        );
    },

    down: (queryInterface) => {
        return queryInterface.bulkDelete('pays');
    },
};
